### ISSUE TITLE
Is there anything for English to English Paraphrasing?

### ISSUE THREAD

**Issue by JafferWilson** [goodmami/xmt#1]
Hello,
I have seen you repository READ.ME file and what I observed is that your project shows only Japanese to English. What If I want to have for English to English Paraphrase. Kindly, guide me What I can do. Thank you in advance.

**Comment by goodmami** [comment]
While this project's primary purpose is for machine translation (e.g., Japanese to English), it also accommodates parsing, generation, and paraphrasing. Also, this XMT project is built on top of the tools that actually process the data ([ACE](http://sweaglesw.org/linguistics/ace/), for one) and the grammars that define the rules for processing a language.

The example in the README (under ["Usage"](https://github.com/goodmami/xmt#usage)) in fact does English to English paraphrasing. The ERG is a grammar for English, so the first command initializes a workspace using the ERG for parsing (and, unless otherwise specified, the grammar for parsing is also used for paraphrasing ("rephrasing")) and imports the `mrs` profile in for processing:

```bash
./xmt.sh init --parse="-g ~/erg/erg.dat" \
              --ace-bin=/path/to/ace \
              my-workspace \
              ~/erg/tsdb/gold/mrs
```

The second command parses the `mrs` profile:

```bash
./xmt.sh parse my-workspace/mrs
```

The third command rephrases (paraphrases) from the results of parsing:

```bash
./xmt.sh rephrase my-workspace/mrs
```

and the final command evaluates the results:

```bash
./xmt.sh evaluate --coverage --bleu my-ws/mrs/
```

Note that currently XMT only imports [[incr tsdb()]](http://moin.delph-in.net/ItsdbTop) profiles.

**Comment by JafferWilson** [comment]
Thank you.
